@startuml

participant ":WeekView" as WeekView
participant ":UiRenderer" as UiRenderer

' Printing of Week Header
WeekView -> UiRenderer: printWeekHeader()

activate UiRenderer
UiRenderer -> UiRenderer: printHorizontalDivider()
activate UiRenderer
UiRenderer --> UiRenderer
deactivate UiRenderer

UiRenderer -> UiRenderer: printHeaderRow()
activate UiRenderer
UiRenderer --> UiRenderer
deactivate UiRenderer

opt !isMonthView
    UiRenderer -> UiRenderer: printDateRow()
    activate UiRenderer
    UiRenderer --> UiRenderer
    deactivate UiRenderer
end

UiRenderer -> UiRenderer: printHorizontalDivider()
activate UiRenderer
UiRenderer --> UiRenderer
deactivate UiRenderer

UiRenderer --> WeekView
deactivate UiRenderer


' Printing of Week Body
WeekView -> UiRenderer: printWeekBody()
activate UiRenderer

UiRenderer -> UiRenderer: printTasksInWeek()
activate UiRenderer
UiRenderer --> UiRenderer
deactivate UiRenderer

UiRenderer -> UiRenderer: printHorizontalDivider()
activate UiRenderer
UiRenderer --> UiRenderer
deactivate UiRenderer

UiRenderer --> WeekView
deactivate UiRenderer

hide footbox
@enduml
