@startuml

skinparam classAttributeIconSize 0

class TaskManagerException extends Exception {

{static} + NOT_CURRENT_WEEK_MESSAGE : String
{static} + NOT_CURRENT_MONTH_MESSAGE : String
{static} + NO_TASKS_MESSAGE : String


+ TaskManagerException(errorMessage : String)

{static} + checkIfDateTimeInFormat(dateTime : String) : void
{static} + checkIfDateInFormat(date : String) : void
{static} + checkIfTimeInFormat(time : String) : void
{static} + checkIfDateInCurrentWeek(date : LocalDate, weekView : WeekView) : void
{static} + checkIfTaskExistsInCurrentDate(dayTasks: List<Task>, index: int) : void
{static} + checkIfDateInCurrentMonth(date : LocalDate) : void
{static} + checkIfDateHasTasks(dayTasks : List<Task>) : void

}

class MarkTaskException extends TaskManagerException {

{static} + TASK_INDEX_OUT_OF_RANGE_FOR_DAY_WITH_TASKS_MESSAGE : String
{static} + TASK_INDEX_WITH_NO_TASKS_MESSAGE : String

+ MarkTaskException(errorMessage : String)

{static} + checkIfTaskIndexIsValidForMarkingTask(dayTasks : List<Task>, taskIndex : int) : void

}

class SetPriorityException extends TaskManagerException {

{static} + TASK_INDEX_OUT_OF_RANGE_FOR_DAY_WITH_TASKS_MESSAGE : String
{static} + TASK_INDEX_WITH_NO_TASKS_MESSAGE : String
{static} + INVALID_PRIORITY_MESSAGE : String

+ SetPriorityException(errorMessage : String)

{static} + checkIfTaskIndexIsValidForPriority(dayTasks : List<Task>, taskIndex : int) : void
{static} + checkIfPriorityIsValid(priority : String) : void

}

class StorageFileException extends Exception {

+ StorageFileException(errorMessage : String)

{static} + checkStorageTextDateFormat(date : String) : void

}

hide circle

@enduml